// Generated by scripts/update-rlottie.sh — do not edit by hand.
// Identifies the vendored rlottie revision (Chunk 0.2). Consumed by the
// deterministic cache key (Chunk 5.3) and getNativeVersion() (Chunks 2.4/3.4).
#pragma once

namespace rnrlottie {

// Full commit SHA of the vendored rlottie source in cpp/third_party/rlottie/.
inline constexpr char kRlottieCommit[] = "2365f5671b67791fc179818fd11b180d79aec612";

}  // namespace rnrlottie
